version: "2"
services:
  grafana:
    image: grafana/grafana:6.5.0
    hostname: grafana
    container_name: grafana
    restart: always 
    ports:
      - "3000:3000"
 #   volumes:
 #     - "./graf:/var/lib/grafana:rw"
  prometheus:
    image: prom/prometheus
    hostname: prometheus
    container_name: prometheus
    restart: always 
    ports:
      - "9090:9090"
    volumes:
      - "./prom/prometheus.yml:/etc/prometheus/prometheus.yml"
  nodeexporter:
    image: prom/node-exporter
    hostname: node-exporter
    container_name: node-exporter
    restart: always 
    ports:
      - "9100:9100"
    command: --collector.systemd  --collector.processes
    entrypoint: node_exporter  
    pid: host

  cadvisor:
    image:   gcr.io/google-containers/cadvisor:v0.35.0
    hostname: cadvisor
    container_name: cadvisor
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - "/:/rootfs:ro"
      - "/var/run:/var/run:ro"
      - "/sys:/sys:ro"
      - "/var/lib/docker/:/var/lib/docker:ro"
      - "/dev/disk/:/dev/disk:ro"
